/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/GridManager")]
    [LuaRegisterType(0xfde923a3b6094740, typeof(LuaBehaviour))]
    public class GridManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "793a1659011eca74cbb7b96ae8ddf7fb";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("60077687dd2352042827328a5da8a2ca")]
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Object> m_Grids = default;
        [SerializeField] public UnityEngine.GameObject m_TreasureChest = default;
        [SerializeField] public UnityEngine.GameObject m_Trash = default;
        [SerializeField] public UnityEngine.GameObject m_Coins = default;
        [SerializeField] public UnityEngine.GameObject m_Nothing = default;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.GameObject> m_Items = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_Grids),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_TreasureChest),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_Trash),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_Coins),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_Nothing),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_Items),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/GridManager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
