/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/InventoryModule")]
    [LuaRegisterType(0x720333ff51605d0b, typeof(LuaBehaviour))]
    public class InventoryModule : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "bae1f9722b7017f48abc80f1f10b6383";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Boolean m_ShovelEquipped = false;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_ShovelEquipped),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/InventoryModule/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
