/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/ItemBehavior")]
    [LuaRegisterType(0xa6c98b12efc32320, typeof(LuaBehaviour))]
    public class ItemBehavior : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "93ee58479658f4e42815e909db576830";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_itemType = "";
        [SerializeField] public UnityEngine.Texture m_itemImage = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_itemType),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_itemImage),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/ItemBehavior/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
