/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/PopupUIModule")]
    [LuaRegisterType(0x1bec1d57ca2b5c0f, typeof(LuaBehaviour))]
    public class PopupUIModule : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "671c5d166425d4342b6ad087fe2db653";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Collections.Generic.List<UnityEngine.Texture> m_ItemImages = default;
        [SerializeField] public UnityEngine.Texture m_PlaceholderImage = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_ItemImages),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_PlaceholderImage),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/PopupUIModule/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
