/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/UpgradeModule")]
    [LuaRegisterType(0xf31477443879e433, typeof(LuaBehaviour))]
    public class UpgradeModule : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "f5599dd79f551a744a0a30552edf8f38";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("dc991eb5859fc934484141ee7cad0eb0")]
        [SerializeField] public UnityEngine.Object m_StoreButton = default;
        [LuaScriptPropertyAttribute("df7f4cc8c99b47547b1dbccc3f3b8408")]
        [SerializeField] public UnityEngine.Object m_UpgradeUI = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_StoreButton),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_UpgradeUI),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/UpgradeModule/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
