/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/WinManager")]
    [LuaRegisterType(0x55f25ba3cb3fa298, typeof(LuaBehaviour))]
    public class WinManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "08d76d9fcf5dbe045aae2fa2fc4722c1";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("c6aecc00c66cfb44b83db01d50e3fc53")]
        [SerializeField] public UnityEngine.Object m_WinsUI = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_WinsUI),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/WinManager/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
